### ISSUE TITLE
Fail to connect

### ISSUE THREAD

**Issue by wilson13349315** [nhcb/entsog-py#11]
Once I used the package to get the data in Dataframe, the error shows "Max retries exceeded with url"

**Comment by nhcb** [comment]
Hi Wilson,

Thanks for using entsog-py. 

I believe they have changed something internally, as for the past days I have noticed I also get an error:
![image](https://user-images.githubusercontent.com/59085665/215117564-1c6d3c44-9c5d-4893-b0be-29ee0655de66.png)
I will look into it, will report back.

**Comment by nhcb** [comment]
Drafted a new release, please update to version 1.0.2; this fixes the issue.

**Comment by wilson13349315** [comment]
Hi nhcb,

Thanks for your fast response and I do notice that you added "verify =
False" as temporary solution. I know about this SSL certificate as well.

But we should only disable SSL certificate validation during local
development or testing as it could make your application vulnerable to
man-in-the-middle attacks.

So from what I read, "retry" method is suggested. However, I think you have
already implemented the function of "retry", so.. I am unsure now what
would be the best option here.

Thanks,
Wilson

**Comment by nhcb** [comment]
Hi Wilson,

Thanks for looking into this as well. It's indeed a temporary solution until I find something better, but I am unsure of where this suddenly has originated from. 

The harmfullness of this solution is really only trivial, as we are not sending any sensitive data over. See https://stackoverflow.com/questions/41740361/is-it-safe-to-disable-ssl-certificate-verification-in-pythonss-requests-lib, but I agree this should be a temporary fix. If you have any suggestions please open a request.
