### ISSUE TITLE
Using proxy with EntsogPandasClient

### ISSUE THREAD

**Issue by risosoky** [nhcb/entsog-py#14]
Hello, is there any way how to use proxy with EntsogPandasClient similarly as in ENTSOE-py or EntsogRawClient? Thanks for an answer :)

**Comment by nhcb** [comment]
I have not felt the need to add it as I have no use case. But you can adjust your script the following:
```
client = EntsogPandasClient()
client.session.proxies = {'http' : ..., 'https' : ...}
```

I have not tested it, but I believe this would work.

**Comment by risosoky** [comment]
Thanks, it works well.
