### ISSUE TITLE
Day ahead prices

### ISSUE THREAD

**Issue by OBerghmans** [nhcb/entsog-py#16]
Hi,

Probably not an issue with the package, but rather on my knowledge side.

I stumbled upon this repository in my search for calculating/retrieving day ahead prices for energy and gas. With the entsoe API I managed to retrieve the day ahead prices. Is this also possible with the entsog API, and by extension with this package?

More specifically, I'm trying to get the day ahead prices for ZTP in Belgium (both ZTP Day Ahead and ZTP Weekend).

My apologies if this question is too far out of scope. I tried several queries using your library and managed to get a very extensive list of operator points (related to Fluxys/ZTP/...) and tariffs (although I had to revert to requests queries to narrow down the search scope so that the query would not take longer than 5 seconds). But none of those made me any wiser. Do you have any directions? (Hoping you would have gather some knowledge around this by building this library)

Thanks,
Olivier

**Comment by nhcb** [comment]
Hi Olivier,

These prices are not incorporated in the ENTSOG platform. The tariffs you mentioned are merely the cost accompanied with utilizing a certain pipeline/point (as far as I know). 

You should look towards ICE, they have (albeit not historical) the prices for TTF, ZTP and other gas hubs.

Kind regards,

Nicky

**Comment by OBerghmans** [comment]
Hi Nicky,

That is unfortunate! Thanks for taking the time to answer and giving me a pointer on where to search next.
Either way, nice job on this package! You managed to create a nice set of functionality within it already.

Kind regards,
Olivier
