### ISSUE TITLE
Tried the example without succes

### ISSUE THREAD

**Issue by fcontino** [nhcb/entsog-py#5]
Hi, 

I've found you library very useful. However, when trying to run the example, it raises an error for plot_utils not being part of entsog. Could you help me with this?

Thanks.

**Comment by nhcb** [comment]
Hi, thanks for using the package. It is due to me not having updated it on the PyPi yet. I am a novice when it comes to releasing packages, it's also an extra dependency (the plots stuff) I am not sure I want to add. I will update and push to PyPi it later this week, and close the issue.

**Comment by nhcb** [comment]
In the meantime, if you want you can just copy the plots_util functions in entsog/plots_util.py in your file and you'll be able to run the example (after installing plotnine).
